spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  mvc:
    static-path-pattern: /**
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    serialization:
      fail-on-empty-beans: false
  mail:
    host: smtp.yandex.ru
    port: 465
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true

security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    refresh-expiration-ms: 86400000
    jwt-expiration-ms: 3600000
  session:
    expiration-ms: 28800000 # if user didn't agree to remember them
    remembered-expiration-ms: 2592000000 # if user agree to remember them

logging:
  file:
    name: app.log

springdoc:
  api-docs:
    path: /api-docs

server:
  port: ${SERVICE_PORT}