spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  mvc:
    static-path-pattern: /**
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    serialization:
      fail-on-empty-beans: false
  config:
    import: optional:file:.env[.yml]

security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}

logging:
  file:
    name: app.log


springdoc:
  api-docs:
    path: /api-docs

server:
  port: 8088